stages:
  - build

build:
  stage: build
  script:
    - cibuilder build
  only:
    - /^issue-[-a-zA-Z0-9]*$/
    - /^feature-[-a-zA-Z0-9]*$/
    - /^hotfix-[-a-zA-Z0-9]*$/
    - /^release-[-a-zA-Z0-9]*$/
    - for_demo
    - release
    - develop
    - /^\d+\.\d+\.\d+$/
    - /^dev_.*$/
    - /^prod-\d+\.\d+\.\d+$/
    - /^dev_*/

